branches:
  - name: main
    prerelease: false
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'
  - - '@semantic-release/exec'
    - publishCmd: docker push $IMAGE:${nextRelease.version}
