apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
spec:
  interval: 5m
  chart:
    spec:
      chart: flagger
      sourceRef:
        kind: HelmRepository
        name: flagger
      interval: 60m
  values:
    meshProvider: linkerd
    metricsServer: http://prometheus.linkerd-viz.svc:9090
    crd:
      create: false
