apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flagger
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: linkerd-viz
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/flux/apps/flagger
  prune: true
  wait: true
  timeout: 5m0s
