apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: realworld
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: cert-manager
    - name: ingress-nginx
    - name: lets-encrypt-staging
    - name: linkerd
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/flux/apps/realworld
  prune: true
  wait: true
  timeout: 5m0s
