---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/flux/apps/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
