apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkerd
configurations:
  - kustomizeconfig.yaml
resources:
  #- namespace.yaml # created via terraform now for added secrets
  - linkerd-stable-repository.yaml
  - linkerd-crds-release.yaml
  - linkerd-release.yaml
  - linkerd-smi-repository.yaml
  - linkerd-smi-release.yaml
