apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-crds
spec:
  interval: 5m
  chart:
    spec:
      version: "1.x"
      chart: linkerd-crds
      sourceRef:
        kind: HelmRepository
        name: linkerd2-stable
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  # https://artifacthub.io/packages/helm/linkerd2/linkerd-crds
