---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: realworld
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: realworld
  policy:
    semver:
      range: '>=1.0.0 <2.0.0'
