apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hpa.yaml
  - deployment.yaml
  - pdb.yaml
  - service.yaml
  - cert-secret.yaml
  - ingress.yaml
  - image-repo.yaml
  - image-policy.yaml
  - image-update-automation.yaml
