apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
resources:
  - secrets-store-csi-driver-repository.yaml
  #- csi-secrets-store-release.yaml

