apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      version: "1.x"
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
