apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metrics-server
configurations:
  - kustomizeconfig.yaml
resources:
  - namespace.yaml
  - metrics-server-repository.yaml
  - metrics-server-release.yaml
