name: CI Build

on:
  push:
    branches:
      - main

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/realworld

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: |-
          npm install \
            semantic-release \
            @semantic-release/exec \
            @semantic-release/changelog \
            @semantic-release/git

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Release
        run: npx semantic-release
