name: Renovate
on:
  workflow_dispatch: {}
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.238.3
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
