apiVersion: apps/v1
kind: Deployment
metadata:
  name: realworld
  namespace: default
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: realworld
  template:
    metadata:
      labels:
        app: realworld
    spec:
      imagePullSecrets:
      - name: docker-ghcr
      containers:
      - name: realworld
        image: ghcr.io/juldanherglo/realworld:1.0.1
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /
            port: http
        livenessProbe:
          httpGet:
            path: /
            port: http
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: realworld-db
              key: DATABASE_HOST
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: realworld-db
              key: DATABASE_PASSWORD
        resources:
          limits:
            cpu: 1000m
            memory: 768Mi
          requests:
            cpu: 100m
            memory: 256Mi
