apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: realworld
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: realworld
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
