apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: realworld
  namespace: realworld
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: realworld
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
