---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: realworld
  namespace: default
spec:
  image: ghcr.io/stefanprodan/podinfo
  interval: 1m0s
  secretRef:
    name: docker-ghcr

