apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hpa.yaml
  - deployment.yaml
  - service.yaml
  #- alb.yaml
  - image-repo.yaml
  - image-policy.yaml
  - image-update-automation.yaml
